name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        efcore: [ '1.0.0', '1.1.6', '2.0.0', '2.2.6', '3.0.0', '3.1.8' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore --property:EntityFrameworkCoreVersion=${{matrix.efcore}}
    - name: Build
      run: dotnet build --configuration Release --no-restore --property:EntityFrameworkCoreVersion=${{matrix.efcore}}
    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal --property:EntityFrameworkCoreVersion=${{matrix.efcore}}
