name: Build

env:
  DOTNET_NOLOGO: 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        efcore: ['3.1.23', '5.0.15']
    env:
      EntityFrameworkCoreVersion: ${{matrix.efcore}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:TreatWarningsAsErrors=true
    - name: Run Tests
      run: dotnet test --configuration Release --no-build
